kind: pipeline
type: docker
name: default

steps:
  - name: build-and-push
    image: plugins/docker
    settings:
      repo: boro/mysql-backup-s3
      tags:
        - latest
      username:
        from_secret: dockerhub_username
      password:
        from_secret: dockerhub_password
      dockerfile: Dockerfile
    when:
      branch:
        - main
      event:
        - push
